version: '3.8'

services:
  fastapi_ylab:
    container_name: fastapi_ylab
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${PROD_DATABASE_URL}"
#      CONFIG_FILE: "config.yaml"
    entrypoint: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
#    volumes:
#      - .:/app
    networks:
      - ylab_network
    ports:
      - "8000:8000"
    depends_on:
      postgres_ylab:
        condition: service_healthy

  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "ylab"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${PGUSER}"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "ylab"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

networks:
  ylab_network:
    name: ylab_network
