version: '3.8'

services:
  fastapi_ylab:
    container_name: fastapi_ylab
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      CONFIG_FILE: "config.yaml"
    entrypoint: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    networks:
      - ylab_network
    ports:
      - "8000:8000"
    depends_on:
      postgres_ylab:
        condition: service_healthy

  postgres_ylab:
    container_name: postgres_ylab
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "ylab"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passwd"
      PGUSER: "postgres"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "ylab"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  ylab_network:
    name: ylab_network
